### Send POST request with json body
POST http://192.168.64.10:3000/meetup
Content-Type: application/json

{
  "title": "This is the second meetup",
  "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Stadtbild_M%C3%BCnchen.jpg/2560px-Stadtbild_M%C3%BCnchen.jpg",
  "address": "Meetupstreet 5, 12345 Meetup City",
  "description": "This is a first, amazing meetup which you definitely should not miss. It will be a lot of fun!"
}