### Login user
POST https://api.bunny.com:3000/login
Content-Type: application/json

{
  "email": "florinc@bunny.com",
  "password": "1234"
}

### Logout user
GET https://api.bunny.com:3000/logout
Content-Type: application/json

### Get books
GET https://api.bunny.com:3000/books
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZsb3JpbmNAYnVubnkuY29tIiwicGFzc3dvcmQiOiIxMjM0IiwiaWF0IjoxNjQ4ODQ2MzkwLCJleHAiOjE2NDg4NDk5OTB9.lGUxrX4yhCTBGrdWSj0aPJ7R8uHD_srNULkbyGDcFmc; Domain=bunny.com; Path=/; HttpOnly; Secure

### Login options
OPTIONS https://api.bunny.com:3000/

